### ISSUE TITLE
EnderIO: Found the following problem(s) with your installation: "An unsupportted old RF API is installed (1.7.10R1.0.1 from RemainInMotion-2.8.8.jar). Ender IO needs at least 1.7.10R1.0.2 and will NOT work with older versions." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

### ISSUE THREAD

**Issue by davidcollins1989** [Vaygrim/vcs3#5] opened 2015-12-16 15:09 UTC
http://paste.ee/p/tLHBR

**Comment by RedeyeTheGoblin** [comment] 2015-12-16 15:22
Thats just an information message - the actual crash is caused by EnderIO Addons and has been fixed in VC3-1.1.

Please update to that version, and if the crash still occurs let me know.

**Comment by Greylocke** [comment] 2015-12-17 17:00
Fixed with updated EnderIO Addons in v1.1

**Closed as completed by Greylocke** 2015-12-17 17:00 UTC
